key_size: 128
public_key: "public.pem" # file to store public key
private_key: "private.pem" # file to store private key
aes_key: "aes_keys_chain.bin" # the AES key is encrypted using the private key
directories:
    - ./Directories/Documents
    - ./Directories/Downloads
    - ./Directories/Pictures
files:
    - exe
    - docx
    - pdf
    - xlsx
    - txt
